- Media:
    - Jellyfin:
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:8096
        description: Movies & TV
        icon: jellyfin
        widget:
          type: jellyfin
          url: http://{{HOMEPAGE_VAR_SERVER_IP}}:8096
          key: {{HOMEPAGE_VAR_JELLYFIN_API_KEY}}
          enableNowPlaying: true
          enableBlocks: true

- Management:
    - Radarr:
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:7878
        description: Movies
        icon: radarr
        widget:
          type: radarr
          url: http://{{HOMEPAGE_VAR_SERVER_IP}}:7878
          key: {{HOMEPAGE_VAR_RADARR_API_KEY}}
          enableQueue: true

    - Sonarr:
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:8989
        description: TV Shows
        icon: sonarr
        widget:
          type: sonarr
          url: http://{{HOMEPAGE_VAR_SERVER_IP}}:8989
          key: {{HOMEPAGE_VAR_SONARR_API_KEY}}
          enableQueue: true

    - Prowlarr:
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:9696
        description: Indexers
        icon: prowlarr
        widget:
          type: prowlarr
          url: http://{{HOMEPAGE_VAR_SERVER_IP}}:9696
          key: {{HOMEPAGE_VAR_PROWLARR_API_KEY}}

- Download:
    - qBittorrent:
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:8080
        description: Torrents
        icon: qbittorrent
        widget:
          type: qbittorrent
          url: http://{{HOMEPAGE_VAR_SERVER_IP}}:8080
          username: admin
          password: {{HOMEPAGE_VAR_QBIT_PASSWORD}}
          enableQueue: true

- System:
    - Portainer:
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:9000
        description: Docker Manager
        icon: portainer
        widget:
          type: portainer
          url: http://{{HOMEPAGE_VAR_SERVER_IP}}:9000
          key: {{HOMEPAGE_VAR_PORTAINER_API_KEY}}
          enableStatus: true
